"""interesse com mensagem e unico por animal e tutor

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 18:29:53.066550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interesses', sa.Column('mensagem', sa.String(length=500), nullable=True))
    op.create_unique_constraint('uq_interesses_animal_tutor', 'interesses', ['animal_id', 'tutor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_interesses_animal_tutor', 'interesses', type_='unique')
    op.drop_column('interesses', 'mensagem')
    # ### end Alembic commands ###
